# Generated by Django 5.0.1 on 2026-02-26 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('subtitle', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('source_url', models.URLField(blank=True, max_length=1000, null=True, unique=True)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('author', models.CharField(default='RraSHI AI', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_breaking', models.BooleanField(default=True)),
                ('is_hero', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.district')),
            ],
        ),
    ]
